version: '2'

networks:
  Blog:
    ipam:
      config:
        - subnet: 172.66.0.0/24

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PJjhVpnW41lPQ2Y
    ports:
      - 5432:5432
    networks:
      Blog:
        ipv4_address: 172.66.0.5

  Blog:
    image: blogweb:latest
    volumes:
      - ./DjangoBlog:/app/DjangoBlog
    ports:
      - 8000:8000
    command: /bin/bash /opt/start.sh
    links:
      - db
    networks:
      Blog:
        ipv4_address: 172.66.0.8
