# Generated by Django 4.1.4 on 2022-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialsName', models.CharField(max_length=25)),
                ('SocialsURL', models.URLField()),
            ],
        ),
    ]
