# Generated by Django 4.1.4 on 2022-12-14 21:35

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutName', models.CharField(max_length=255)),
                ('P1', models.CharField(max_length=255)),
                ('Header', models.CharField(max_length=255)),
                ('P2', models.CharField(max_length=255)),
                ('body', mdeditor.fields.MDTextField(blank=True, null=True)),
            ],
        ),
    ]
